/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Application program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/* MEMORY CONFIGURATION */
#define APP_ADDRESS   0x0800C000

/* RCC REGISTERS */
#define RCC_AHB1ENR     (*(volatile uint32_t*)(0x40023830))
#define RCC_APB1ENR     (*(volatile uint32_t*)(0x40023840))

/* GPIOA REGISTERS */
#define GPIOA_MODER     (*(volatile uint32_t*)(0x40020000))
#define GPIOA_ODR       (*(volatile uint32_t*)(0x40020014))
#define GPIOA_AFRL      (*(volatile uint32_t*)(0x40020020))

/* USART2 REGISTERS */
#define USART2_SR       (*(volatile uint32_t*)(0x40004400))
#define USART2_DR       (*(volatile uint32_t*)(0x40004404))
#define USART2_BRR      (*(volatile uint32_t*)(0x40004408))
#define USART2_CR1      (*(volatile uint32_t*)(0x4000440C))

/* FUNCTION DECLARATIONS */
void uart2_init(void);
void uart2_write_char(char c);
void uart2_write_string(const char *str);
void led_init(void);
void led_toggle(void);
void delay(void);

/* MAIN */
int main(void)
{
    uart2_init();
    led_init();

    uart2_write_string("\r\nAPP : Started @ 0x0800C000\r\n");

    while (1)
    {
        led_toggle();
        uart2_write_string("APP : Running\r\n");
        delay();
    }
}

/* UART2 INIT
   PA2 -> TX */
void uart2_init(void)
{
    /* Enable GPIOA clock */
    RCC_AHB1ENR |= (1 << 0);

    /* Enable USART2 clock */
    RCC_APB1ENR |= (1 << 17);

    /* PA2 = alternate function mode */
    GPIOA_MODER &= ~(3 << 4);
    GPIOA_MODER |=  (2 << 4);

    /* PA2 = AF7 */
    GPIOA_AFRL &= ~(0xF << 8);
    GPIOA_AFRL |=  (7 << 8);

    /* 9600 baud for 16 MHz */
    USART2_BRR = 0x0683;

    /* Enable transmitter */
    USART2_CR1 |= (1 << 3);

    /* Enable USART */
    USART2_CR1 |= (1 << 13);
}

/* UART SEND CHAR */
void uart2_write_char(char c)
{
    while (!(USART2_SR & (1 << 7)));

    USART2_DR = c;
}

/* UART SEND STRING */
void uart2_write_string(const char *str)
{
    while (*str)
    {
        uart2_write_char(*str++);
    }
}

/* LED INIT
   PA5 -> OUTPUT */
void led_init(void)
{
    /* Enable GPIOA clock */
    RCC_AHB1ENR |= (1 << 0);

    /* PA5 = output mode */
    GPIOA_MODER &= ~(3 << 10);
    GPIOA_MODER |=  (1 << 10);
}

/* LED TOGGLE */
void led_toggle(void)
{
    GPIOA_ODR ^= (1 << 5);
}

/* SIMPLE DELAY */
void delay(void)
{
    for (volatile uint32_t i = 0; i < 1000000; i++);
}
