/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/* MEMORY CONFIGURATION  */
#define HEADER_ADDRESS   0x08008000U
#define APP_ADDRESS      0x0800C000U
#define SRAM_START       0x20000000U
#define SRAM_END         0x20020000U

typedef void (*app_func_t)(void);

/*  RCC REGISTERS  */
//#define RCC_BASE        0x40023800U
#define RCC_AHB1ENR     (*(volatile uint32_t*)(0x40023830))
#define RCC_APB1ENR     (*(volatile uint32_t*)(0x40023840))

/*  GPIOA REGISTERS  */
//#define GPIOA_BASE      0x40020000U
#define GPIOA_MODER     (*(volatile uint32_t*)(0x40020000))
#define GPIOA_AFRL      (*(volatile uint32_t*)(0x40020020))

/*   USART2 REGISTERS   */
//#define USART2_BASE     0x40004400U
#define USART2_SR       (*(volatile uint32_t*)(0x40004400))
#define USART2_DR       (*(volatile uint32_t*)(0x40004404))
#define USART2_BRR      (*(volatile uint32_t*)(0x40004408))
#define USART2_CR1      (*(volatile uint32_t*)(0x4000440C))

/*  SCB VTOR REGISTER    */
#define SCB_VTOR        (*(volatile uint32_t*)0xE000ED08U)


/*  FUNCTION DECLARATIONS  */
void uart2_init(void);
void uart2_write_char(char c);
void uart2_write_string(const char *str);
uint8_t is_application_valid(void);
void jump_to_application(void);
void delay(void);

/*  MAIN   */
int main(void)
{
    uart2_init();

    uart2_write_string("\r\nBOOT: Started\r\n");
    uart2_write_string("BOOT: Checking application\r\n");

    if (is_application_valid())
    {
        uart2_write_string("BOOT: App valid\r\n");
        delay();

        jump_to_application();
    }
    else
    {
        uart2_write_string("BOOT: Invalid app\r\n");

        while (1)
        {
            uart2_write_string("BOOT: Staying here\r\n");
            delay();
        }
    }
}



/* UART2 INIT
   PA2 -> TX  */
void uart2_init(void)
{
    /* Enable GPIOA clock */
    RCC_AHB1ENR |= (1 << 0);

    /* Enable USART2 clock */
    RCC_APB1ENR |= (1 << 17);

    /* PA2 = alternate function mode */
    GPIOA_MODER &= ~(3 << 4);
    GPIOA_MODER |=  (2 << 4);

    /* PA2 = AF7 */
    GPIOA_AFRL &= ~(0xF << 8);
    GPIOA_AFRL |=  (7 << 8);

    /* 9600 baud for 16 MHz */
    USART2_BRR = 0x0683;

    /* Enable transmitter */
    USART2_CR1 |= (1 << 3);

    /* Enable USART */
    USART2_CR1 |= (1 << 13);
}



/*  UART SEND CHAR  */
void uart2_write_char(char c)
{
    while (!(USART2_SR & (1 << 7)));

    USART2_DR = c;
}

/* UART SEND STRING  */
void uart2_write_string(const char *str)
{
    while (*str)
    {
        uart2_write_char(*str++);
    }
}


/*  APP VALIDATION   */
uint8_t is_application_valid(void)
{
    uint32_t app_sp;

    app_sp = *(volatile uint32_t*)APP_ADDRESS;

    if (app_sp == 0xFFFFFFFF)
        return 0;

    if (app_sp < SRAM_START || app_sp > SRAM_END)
        return 0;

    return 1;
}

/*   JUMP TO APP  */
void jump_to_application(void)
{
    uint32_t app_sp;
    uint32_t app_reset;

    app_sp    = *(volatile uint32_t*)APP_ADDRESS;
    app_reset = *(volatile uint32_t*)(APP_ADDRESS + 4);

    uart2_write_string("BOOT: Set VTOR\r\n");

    SCB_VTOR = APP_ADDRESS;

    uart2_write_string("BOOT: Set MSP\r\n");

    __asm volatile("msr msp, %0" : : "r"(app_sp));

    uart2_write_string("BOOT: Jumping\r\n");

    delay();

    app_func_t app_entry = (app_func_t)app_reset;

    app_entry();
}



/*  SIMPLE DELAY  */
void delay(void)
{
    for (volatile uint32_t i = 0; i < 1000000; i++);
}
